# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='one_signal_app_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='one_signal_rest_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
