# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180201_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_review', models.BooleanField(default=True)),
                ('activity_review_buffer', models.IntegerField(default=60)),
                ('activity_start', models.BooleanField(default=True)),
                ('activity_end', models.BooleanField(default=True)),
                ('activity_reject', models.BooleanField(default=True)),
                ('activity_accept', models.BooleanField(default=True)),
                ('activity_suspend', models.BooleanField(default=True)),
                ('activity_resume', models.BooleanField(default=True)),
                ('activity_abort', models.BooleanField(default=True)),
                ('activity_start_buffer', models.IntegerField(default=60)),
                ('average_activity_time', models.IntegerField(default=180)),
                ('enable_accept_reject', models.BooleanField(default=False)),
                ('activity_accept_reject_buffer', models.IntegerField(default=1440)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
