# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerclients_customerpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpreferences',
            name='activity_review_buffer',
        ),
        migrations.AddField(
            model_name='customerclients',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerclients',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerclients',
            name='weight_pricing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='activity_accept_driver_buffer',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='activity_review_admin_buffer',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='activity_start_driver_buffer',
            field=models.IntegerField(default=5),
        ),
    ]
