# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180417_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclients',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
