# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerclients_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerclients',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
        ),
    ]
