# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 06:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_auto_20180418_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclients',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2018, 5, 9, 6, 34, 1, 151138, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerclients',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerclients',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerclients',
            name='modified_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
