# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customerclients_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerclients',
            name='weight_pricing',
        ),
        migrations.AlterField(
            model_name='customerclients',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
