# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180522_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='bin_dropoff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='bin_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='shift_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='shift_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='waste_collection',
            field=models.BooleanField(default=True),
        ),
    ]
