# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20180530_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='speed_violation_global',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='speed_violations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='territory_violations',
            field=models.BooleanField(default=True),
        ),
    ]
