# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20180605_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclients',
            name='party_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerclients',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
