# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20180611_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='assets_notification',
            field=models.BooleanField(default=False),
        ),
    ]
