# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customerpreferences_value_added_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='address',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='company_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='email',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='fax_no',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='phone_no',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='url',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
