# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20180713_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreferences',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
