# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customerclients_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerclients',
            name='invoice_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
