# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20180720_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerclients',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='invoice_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
