# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20180723_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='shift_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
