# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customerpreferences_shift_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='invoice_number22',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
