# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_customerpreferences_invoice_number22'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='active_inactive_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='attendance_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='site_zone_violations_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
