# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20181011_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='daily_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='monthly_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='weekly_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
