# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20181129_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='diesel_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
