# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='label_de',
        ),
        migrations.RemoveField(
            model_name='options',
            name='label_it',
        ),
        migrations.RemoveField(
            model_name='options',
            name='label_pl',
        ),
    ]
