# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20171123_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='module',
            field=models.IntegerField(default=0),
        ),
    ]
