# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iopderived',
            name='average_temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
