# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iop', '0003_applianceqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applianceqr',
            name='device_id',
        ),
    ]
