# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iop', '0005_auto_20190411_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceqr',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
