# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0066_auto_20190315_1046'),
        ('iop', '0006_applianceqr_created_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('energy_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ec_regular_appliance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.Entity')),
            ],
        ),
    ]
