# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iop', '0009_errorlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='average_temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
