# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iop', '0013_auto_20200225_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogs',
            name='err_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
