# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-04 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0074_auto_20201203_0651'),
        ('iop', '0017_auto_20201022_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconfigurationLockMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('failure_code', models.IntegerField(default=0)),
                ('lock_mode', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.Entity')),
            ],
            options={
                'db_table': 'Reconfiguration_lockMode',
            },
        ),
    ]
