# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20180530_1007'),
        ('options', '0004_auto_20180427_1608'),
        ('customer', '0021_auto_20180723_1110'),
        ('hypernet', '0051_auto_20180703_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actual_start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actual_end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('violations', models.IntegerField(default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee_entity', to='hypernet.Entity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible_entity', to='hypernet.Entity')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_of_task', to='hypernet.Entity')),
                ('task_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_status_id', to='options.Options')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zone_of_task', to='hypernet.Entity')),
            ],
        ),
    ]
