# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0003_auto_20180820_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
