# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0004_tasks_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='site_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='site_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='zone_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='zone_status',
            field=models.BooleanField(default=False),
        ),
    ]
