# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0005_auto_20180906_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='attendance_dtm',
            new_name='site_checkin_dtm',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='check_out_dtm',
            new_name='site_checkout_dtm',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='zone_checkin_dtm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='zone_checkout_dtm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
