# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0006_auto_20180907_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
