# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0007_attendancerecord_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='duration',
            new_name='duration_in_site',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='duration_in_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
