# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0008_auto_20180909_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
