# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20180723_1110'),
        ('user', '0011_auto_20180530_1007'),
        ('hypernet', '0053_auto_20180908_1454'),
        ('ffp', '0009_attendancerecord_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFPDataDailyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('average', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True)),
                ('ambient_temperature', models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True)),
                ('heart_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffp_average_device_id', to='hypernet.Entity')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='average_of_site', to='hypernet.Entity')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='average_of_zone', to='hypernet.Entity')),
            ],
        ),
    ]
