# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20180427_1608'),
        ('ffp', '0010_ffpdatadailyaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeviolations',
            name='active_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_active_status', to='options.Options'),
        ),
    ]
