# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0012_attendancerecord_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='duration_in_site_active',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='duration_in_zone_active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
