# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0013_auto_20180918_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='productive_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
