# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0014_attendancerecord_productive_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_dtm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
