# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0015_attendancerecord_attendance_dtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffpdatadailyaverage',
            name='site_durations_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ffpdatadailyaverage',
            name='site_productivity_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ffpdatadailyaverage',
            name='zone_durations_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ffpdatadailyaverage',
            name='zone_productivity_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ffpdatadailyaverage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffp_average_device_id', to='hypernet.Entity'),
        ),
    ]
