# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0016_auto_20180926_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_type', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffp_attendance_record', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_of_attendance', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_of_attendance', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='employeeviolations',
            name='active_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_active_status', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='employeeviolations',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffp_violation', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='employeeviolations',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_of_violation', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='employeeviolations',
            name='violations_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_violations_type', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='employeeviolations',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_of_violation', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='ffpdatadailyaverage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_of_site', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='ffpdatadailyaverage',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_of_zone', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_of_task', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_id', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_of_task', to='hypernet.Entity'),
        ),
    ]
