# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffp', '0017_auto_20180926_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='duration_in_site',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='duration_in_site_active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='duration_in_zone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='duration_in_zone_active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='productive_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
