# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='msg_title',
            new_name='email_key',
        ),
    ]
