# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('email_manager', '0003_auto_20180109_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user_email_title',
        ),
        migrations.AddField(
            model_name='template',
            name='email_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='email_key',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='from_email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
