# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0004_auto_20180110_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='email_type',
            field=models.CharField(blank=True, choices=[('internal', 'This email will be sent internally and can be mute from edit user. '), ('external', 'This email will be sent to user & can be mute from notification settings.'), ('system', "This email will be sent system wide and can't be mute.")], max_length=200, null=True),
        ),
    ]
