# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
        ('hypernet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group', models.PositiveIntegerField(null=True)),
                ('group_value', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('perform_individually', models.BooleanField(default=True)),
                ('individual_value', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduling_comments', models.TextField(null=True)),
                ('performed_start_time', models.DateTimeField(blank=True, null=True)),
                ('performed_end_time', models.DateTimeField(blank=True, null=True)),
                ('performed_comments', models.TextField(null=True)),
                ('is_on_time', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('avg_milk_yield', models.FloatField(blank=True, null=True)),
                ('avg_standing_time', models.FloatField(blank=True, null=True)),
                ('avg_rumination_time', models.FloatField(blank=True, null=True)),
                ('avg_sitting_time', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('expected_milk', models.FloatField(blank=True, null=True)),
                ('feeding_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('animal_state', models.CharField(max_length=100, null=True)),
                ('state_start_time', models.DateTimeField(null=True)),
                ('state_end_time', models.DateTimeField(null=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('scheduled_start_time', models.TimeField(null=True)),
                ('scheduled_end_time', models.TimeField(null=True)),
                ('scheduled_start_date', models.DateField(null=True)),
                ('scheduled_end_date', models.DateField(null=True)),
                ('scheduled_next_date', models.DateField(null=True)),
                ('perform_individually', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_priority', to='options.Options')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_activity_type', to='options.Options')),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hypernet.HypernetNotification')),
                ('animal', models.ManyToManyField(to='hypernet.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
