# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hypernet', '0002_auto_20171121_0820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0001_initial'),
        ('customer', '0001_initial'),
        ('ioa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assingment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='routine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_routine_type', to='options.Options'),
        ),
        migrations.AddField(
            model_name='animalstates',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_animal_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='animalstates',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalstates',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='animalstates',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalstates',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ioa_supervisor', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='customer_aggregations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Farm_data', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='herd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='herd_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='action_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_status', to='options.Options'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='activity_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_priority', to='options.Options'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_type', to='options.Options'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_animal_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='assigned_to_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='derived_alerts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_alerts', to='hypernet.HypernetNotification'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
