# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioa', '0003_auto_20180104_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalstates',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='animalstates',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='animalstates',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='animalstates',
            name='animal_state_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
