# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioa', '0004_auto_20180109_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalstates',
            name='animal_state_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
