# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import hypernet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ioa', '0006_estruscriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruscriteria',
            name='current_off_datetime',
            field=models.DateTimeField(default=hypernet.utils.estrus_datetime_init),
        ),
        migrations.AlterField(
            model_name='estruscriteria',
            name='current_onset_datetime',
            field=models.DateTimeField(default=hypernet.utils.estrus_datetime_init),
        ),
        migrations.AlterField(
            model_name='estruscriteria',
            name='last_off_datetime',
            field=models.DateTimeField(default=hypernet.utils.estrus_datetime_init),
        ),
        migrations.AlterField(
            model_name='estruscriteria',
            name='last_onset_datetime',
            field=models.DateTimeField(default=hypernet.utils.estrus_datetime_init),
        ),
    ]
