# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hypernet', '0002_auto_20171121_0820'),
        ('user', '0001_initial'),
        ('options', '0001_initial'),
        ('ppp', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmetrics',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='trainingmetrics',
            name='training_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_metrics_status_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='teamderived',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_derived_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='teamderived',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='teamderived',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='teamderived',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='sessionmetrics',
            name='session_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_metrics_status', to='options.Options'),
        ),
        migrations.AddField(
            model_name='sessionmetrics',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_metrics_type_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='sessionmetrics',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppp.TrainingMetrics'),
        ),
        migrations.AddField(
            model_name='reportedinjury',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='reportedinjury',
            name='injury_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='options.Options'),
        ),
        migrations.AddField(
            model_name='reportedinjury',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='reportedinjury',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_injury_player_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerprocessed',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='playerprocessed',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='playerprocessed',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_stats_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerperformancestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerderived',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_derived_competition_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='playerderived',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='playerderived',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='playerderived',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_derived_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_competition_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='match_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_status_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_venue_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='injury',
            name='backup_substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_backup_player_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='injury',
            name='competition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_competition_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='injury',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='injury_position_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='injury_status_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='injury',
            name='injury_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='injury_type_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='injury',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_match_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='injury',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='injury',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_player_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='injury',
            name='reported_injury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppp.ReportedInjury'),
        ),
    ]
