# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171127_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
