# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_module_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_module',
            field=models.IntegerField(default=1),
        ),
    ]
