# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0014_auto_20171221_1349'),
        ('user', '0004_user_preferred_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hypernet.Entity'),
        ),
    ]
