# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_associated_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_signal_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
