# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_one_signal_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_module',
            field=models.FloatField(default=1.0),
        ),
    ]
