# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180416_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associated_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_user', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
