# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180507_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associated_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associated_user', to='hypernet.Entity'),
        ),
    ]
