# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180530_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='android_device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ios_device_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
