# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_customerpreferences_diesel_price'),
        ('user', '0013_userconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
