# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userconfirmation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='active',
            field=models.NullBooleanField(default=False),
        ),
    ]
