# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('hypernet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticAggregations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('total_volume_consumed', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('total_trips', models.IntegerField(null=True)),
                ('total_jobs_completed', models.IntegerField(null=True)),
                ('total_jobs_failed', models.IntegerField(null=True)),
                ('total_maintenances', models.IntegerField(null=True)),
                ('total_violations', models.IntegerField(null=True)),
                ('total_fillups', models.IntegerField(null=True)),
                ('tdist_last24Hrs', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('performance_rating', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_start_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('job_start_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actual_job_start_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_end_timestamp', models.DateTimeField(db_index=True)),
                ('actual_job_end_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_end_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('job_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('job_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('job_volume_consumed', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('job_violations', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('description', models.TextField(default='This is an auto generated text message.')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsDerived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('post_fill_vol', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('pre_fill_vol', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('post_dec_vol', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('pre_dec_vol', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_job', models.BooleanField(default=False)),
                ('truck_odo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trip_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('trip_volume_consumed', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('trip_start_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('trip_start_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_end_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trip_end_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('trip_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_data_device_id', to='hypernet.Entity')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_data_driver_id', to='hypernet.Entity')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_job_id', to='hypernet.Entity')),
            ],
        ),
    ]
