# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hypernet', '0002_auto_20171121_0820'),
        ('user', '0001_initial'),
        ('options', '0001_initial'),
        ('customer', '0001_initial'),
        ('iof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktrips',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='logisticsderived',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='logisticsderived',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_derived_data_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticsderived',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_data_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_data_type_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_jobs_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_job_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='job_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_status', to='options.Options'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='logisticjobs',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_job_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticaggregations',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='logisticaggregations',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_aggregations_device_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticaggregations',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
    ]
