# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0003_auto_20171204_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaggregations',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
