# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0005_auto_20171211_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticjobs',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trucktrips',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
