# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0006_auto_20171215_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_density',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_speed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_temperature',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='last_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='performance_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='tdist_last24Hrs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_fillups',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_jobs_completed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_jobs_failed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_maintenances',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_trips',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_violations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='logisticaggregations',
            name='total_volume_consumed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='logisticjobs',
            name='job_violations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
