# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0007_auto_20171215_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticaggregations',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
