# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0008_auto_20171215_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticjobs',
            old_name='truck',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='logisticjobs',
            old_name='driver',
            new_name='person',
        ),
    ]
