# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0011_logisticaggregations_tvol_last24hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaggregations',
            name='total_decantations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
