# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0012_logisticaggregations_total_decantations'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaggregations',
            name='last_decantation',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticaggregations',
            name='last_fillup',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
