# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0013_auto_20180116_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticjobs',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
