# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0003_options_module'),
        ('customer', '0002_auto_20180201_1056'),
        ('user', '0007_auto_20180124_0931'),
        ('hypernet', '0033_auto_20180305_0531'),
        ('iof', '0015_logisticjobs_maintenance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('start_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('end_lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('volume_consumed', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('violations', models.IntegerField(default=0, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='truck_job_id', to='hypernet.Entity')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='driver_job_id', to='hypernet.Entity')),
                ('scheduled_activity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_template_id',
                                   to='iof.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_route', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_priority',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   related_name='activity_priority_id', to='options.Options')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='activity_type_id', to='options.Options')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
                ('primary_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='activity_schedule_primary_entity',
                                                     to='hypernet.Entity')),
                ('schedule_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='schedule_type_id', to='options.Options')),
                ('secondary_entity',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='activity_secondary_entity', to='hypernet.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iof.ActivitySchedule')),
                ('primary_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='scheduled_activity_primary_entity',
                                                     to='hypernet.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='device',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='maintenance_type',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='module',
        ),
        migrations.RemoveField(
            model_name='logisticjobs',
            name='person',
        ),
        migrations.DeleteModel(
            name='LogisticJobs',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_id',
                                    to='iof.ActivitySchedule'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='activity_status_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='actor_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
