# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0017_activityschedule_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='enable_accept_reject',
            field=models.BooleanField(default=False),
        ),
    ]
