# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0018_activityschedule_enable_accept_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
