# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0020_activityschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='job_start_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
