# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_options_module'),
        ('iof', '0021_activityschedule_job_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='activity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_data_status_id', to='options.Options'),
        ),
    ]
