# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0023_auto_20180411_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydata',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydata',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
