# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0024_auto_20180411_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_lat_long',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_lat_long',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
