# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0028_activity_primary_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
