# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0031_activitydata_action_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='acitvity_end_point',
            new_name='activity_end_point',
        ),
        migrations.RenameField(
            model_name='activityqueue',
            old_name='acitvity_end_point',
            new_name='activity_end_point',
        ),
        migrations.RenameField(
            model_name='activityschedule',
            old_name='acitvity_end_point',
            new_name='activity_end_point',
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='activity_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
