# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0032_auto_20180423_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydata',
            old_name='acitvity_end_point',
            new_name='activity_end_point',
        ),
    ]
