# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0033_auto_20180423_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
