# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0036_activityschedule_days_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='days_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
