# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0039_auto_20180423_1634'),
        ('iof', '0037_auto_20180426_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bincollectiondata',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='bincollectiondata',
            name='truck',
        ),
        migrations.AddField(
            model_name='bincollectiondata',
            name='action_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_action_item_id', to='hypernet.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bincollectiondata',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_actor_id', to='hypernet.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bincollectiondata',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_entity_id', to='hypernet.Entity'),
            preserve_default=False,
        ),
    ]
