# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_options_module'),
        ('iof', '0038_auto_20180426_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincollectiondata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_collection_status_id', to='options.Options'),
        ),
    ]
