# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0039_bincollectiondata_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydata',
            old_name='action_item',
            new_name='action_items',
        ),
        migrations.RenameField(
            model_name='activitydata',
            old_name='person',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='activitydata',
            old_name='end_lat_long',
            new_name='lat_long',
        ),
        migrations.RenameField(
            model_name='activitydata',
            old_name='entity',
            new_name='primary_entity',
        ),
        migrations.RenameField(
            model_name='activitydata',
            old_name='end_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='start_lat_long',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='start_timestamp',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='violations',
        ),
        migrations.RemoveField(
            model_name='activitydata',
            name='volume_consumed',
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='violations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='volume_consumed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
