# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0040_auto_20180427_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
