# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0042_incidentreporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincollectiondata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
