# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0044_auto_20180510_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreporting',
            name='action_items',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
