# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0045_auto_20180510_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bincollectiondata',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iof.Activity'),
        ),
        migrations.AlterField(
            model_name='bincollectiondata',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_actor_id', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='bincollectiondata',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_entity_id', to='hypernet.Entity'),
        ),
    ]
