# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0047_activitydata_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bincollectiondata',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
