# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0050_auto_20180531_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2018, 6, 26, 11, 14, 21, 236325, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
