# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0051_auto_20180703_1645'),
        ('customer', '0015_customerpreferences_value_added_tax'),
        ('iof', '0051_activityschedule_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincollectiondata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_client_id', to='customer.CustomerClients'),
        ),
        migrations.AddField(
            model_name='bincollectiondata',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_collection_contract_id', to='hypernet.Entity'),
        ),
    ]
