# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0053_bincollectiondata_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
