# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20180713_1058'),
        ('user', '0011_auto_20180530_1007'),
        ('iof', '0055_auto_20180717_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.CharField(blank=True, max_length=1000, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_file_client_id', to='customer.CustomerClients')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
            ],
        ),
    ]
