# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0056_invoicesfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesfiles',
            name='module',
        ),
    ]
