# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0057_remove_invoicesfiles_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='trips',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
