# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20181129_0817'),
        ('options', '0004_auto_20180427_1608'),
        ('hypernet', '0059_entity_skip_size'),
        ('user', '0011_auto_20180530_1007'),
        ('iof', '0058_activity_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticMaintenanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=5000, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_data_action_id', to='options.Options')),
                ('cost_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_data_type_id', to='options.Options')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_date_driver', to='hypernet.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='logisticmaintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='logisticmaintenance',
            name='device',
        ),
        migrations.RemoveField(
            model_name='logisticmaintenance',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_driver_id', to='hypernet.Entity'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_status_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_truck_id', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='logisticmaintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='logisticmaintenancedata',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_data_device_id', to='iof.LogisticMaintenance'),
        ),
        migrations.AddField(
            model_name='logisticmaintenancedata',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AddField(
            model_name='logisticmaintenancedata',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_data_truck', to='hypernet.Entity'),
        ),
    ]
