# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0059_auto_20181212_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsderived',
            name='distance_travelled',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='logisticsderived',
            name='fuel_avg',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='logisticsderived',
            name='fuel_consumed',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
