# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iof', '0061_auto_20181214_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticmaintenance',
            name='issued_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticmaintenance',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistic_maintenance_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticmaintenancedata',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logistic_maintenance_data_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
