# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0062_auto_20181215_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fuel_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='waste_collected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydata',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
