# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0063_auto_20181226_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='diesel_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
