# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0064_activity_diesel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='iofshifts',
            name='distance_travelled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='iofshifts',
            name='fuel_avg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='iofshifts',
            name='volume_consumed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
