# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iof', '0065_auto_20190115_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='is_off',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityqueue',
            name='is_on',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityqueue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityqueue',
            name='activity_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iof.ActivitySchedule'),
        ),
    ]
