# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0067_activityqueue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='activity_end_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='suspend_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iof.ActivitySchedule'),
        ),
    ]
