# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0068_auto_20190129_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='u_activity_end_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='u_activity_start_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
