# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0069_auto_20190202_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='u_days_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
