# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0070_activityschedule_u_days_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='multi_days',
            field=models.BooleanField(default=False),
        ),
    ]
