# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0071_activityschedule_multi_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='days_list',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='u_days_list',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
