# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0072_auto_20190213_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='sleep_mode',
            field=models.BooleanField(default=False),
        ),
    ]
