# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0073_activityschedule_sleep_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
