# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0074_activityqueue_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='iofshifts',
            name='trips',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
