# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0076_iofshifts_shift_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='temp_set',
            field=models.BooleanField(default=False),
        ),
    ]
