# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20180427_1608'),
        ('customer', '0026_customerpreferences_diesel_price'),
        ('hypernet', '0064_userentityassignment_is_admin'),
        ('iof', '0077_activityqueue_temp_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSVehicleReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vms', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('trip_start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('loaded_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stops_loaded_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('arrival_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unloaded_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('halting', models.IntegerField(blank=True, default=0, null=True)),
                ('stops_unloading_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('loaded_workshop_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('loaded_workshop_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('loaded_work_order_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('loaded_workshop_remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('loaded_workshop_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('unloaded_workshop_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unloaded_workshop_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unloaded_work_order_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('unloaded_workshop_remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('unloaded_workshop_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('km_loaded', models.IntegerField(blank=True, default=0, null=True)),
                ('km_unloaded', models.IntegerField(blank=True, default=0, null=True)),
                ('office', models.CharField(blank=True, max_length=1000, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerClients')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_destination_id', to='hypernet.Entity')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_driver_entity_id', to='hypernet.Entity')),
                ('loading_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_loading_city_id', to='hypernet.Entity')),
                ('loading_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_loading_location_id', to='hypernet.Entity')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_supervisor_id', to='hypernet.Entity')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_vehicle_entity_id', to='hypernet.Entity')),
                ('vehicle_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cms_vehicle_status_id', to='options.Options')),
                ('vehicle_wheel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cms_vehicle_wheel_type_id', to='options.Options')),
            ],
        ),
    ]
