# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0080_activityschedule_temp_after_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='new_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='old_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
