# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0081_auto_20190620_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityschedule',
            old_name='new_dt',
            new_name='new_end_dt',
        ),
        migrations.RenameField(
            model_name='activityschedule',
            old_name='old_dt',
            new_name='new_start_dt',
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='old_end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='old_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
