# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0082_auto_20190620_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityqueue',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activityqueue',
            name='temperature',
            field=models.IntegerField(blank=True, default=55, null=True),
        ),
    ]
