# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0085_auto_20201012_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='suggestion',
            field=models.NullBooleanField(default=False),
        ),
    ]
