# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0086_activityschedule_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='current_ctt',
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
    ]
