# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0002_auto_20171121_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations',
            name='trans_value_de',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='trans_value_it',
        ),
        migrations.RemoveField(
            model_name='translations',
            name='trans_value_pl',
        ),
    ]
