# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0003_auto_20171123_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hypernetpostdata',
            old_name='distance',
            new_name='distance_travelled',
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='customer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='module',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='accelerometer_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='accelerometer_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='accelerometer_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='breathingrate_avg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='breathingrate_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='breathingrate_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='distance_by_sensor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='harsh_acceleratioin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='harsh_braking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='accelerometer_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='accelerometer_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='accelerometer_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='breathingrate_avg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='breathingrate_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='breathingrate_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='device',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='distance_by_sensor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='harsh_acceleratioin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='harsh_braking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='heartrate_recovery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='heartrate_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='hrv_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='nn_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
