# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0004_auto_20171124_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='heartrate_recovery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='heartrate_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='hrv_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='nn_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
