# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0006_auto_20171127_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetpredata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_device_id', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.DeviceType'),
        ),
    ]
