# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0007_auto_20171127_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='t_timestamp',
            new_name='timestamp',
        ),
    ]
