# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0008_auto_20171127_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypernetnotification',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='hypernetnotification',
            name='player',
        ),
    ]
