# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0009_auto_20171130_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetnotification',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
