# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0010_auto_20171207_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translations',
        ),
    ]
