# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0011_delete_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecalibration',
            name='calibration',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
