# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20171123_0749'),
        ('hypernet', '0013_auto_20171220_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_history_animal_breed', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='date_of_match',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_history_gender_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_history_animal_group', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='lactation_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='lactation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_history_lactation_key', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='last_breeding',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_history_match_type_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='weather_forecast',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
