# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20171123_0749'),
        ('customer', '0001_initial'),
        ('hypernet', '0014_auto_20171221_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('assigned', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='options.Options')),
            ],
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='device_id',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='entityhistory',
            old_name='device_id',
            new_name='device_name',
        ),
    ]
