# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0015_auto_20180101_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hypernet.CustomerDevice'),
        ),
        migrations.AlterField(
            model_name='entityhistory',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hypernet.CustomerDevice'),
        ),
    ]
