# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0016_auto_20180101_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetpostdata',
            name='gyro_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpostdata',
            name='gyro_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpostdata',
            name='gyro_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='gyro_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='gyro_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='gyro_3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
