# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0017_auto_20180101_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceviolation',
            old_name='number_value',
            new_name='threshold_number',
        ),
        migrations.RenameField(
            model_name='deviceviolation',
            old_name='string_value',
            new_name='threshold_string',
        ),
        migrations.AddField(
            model_name='deviceviolation',
            name='trigger_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
