# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0019_auto_20180112_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hypernetpostdata',
            old_name='harsh_acceleratioin',
            new_name='harsh_acceleration',
        ),
    ]
