# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0020_auto_20180112_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceviolation',
            name='next_trigger_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
