# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hypernet', '0022_auto_20180117_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='hypernetnotification',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='notificationgroups',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.HypernetNotification'),
        ),
        migrations.AddField(
            model_name='notificationgroups',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hypernetnotification',
            name='user',
            field=models.ManyToManyField(through='hypernet.NotificationGroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
