# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0023_auto_20180122_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetnotification',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
