# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hypernet', '0026_auto_20180129_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
