# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('options', '0003_options_module'),
        ('hypernet', '0029_auto_20180208_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='maintenance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='options_maintenance_type_id', to='options.Options'),
        ),
        migrations.AddField(
            model_name='entity',
            name='routine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='maintenance_routine_type', to='options.Options'),
        ),
    ]
