# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0030_auto_20180223_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdevice',
            name='primary_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
