# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0031_customerdevice_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
