# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0032_auto_20180228_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_breed', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hypernet.CustomerDevice'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animal_group', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lactation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lactation_key', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='maintenance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options_maintenance_type_id', to='options.Options'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='routine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_routine_type', to='options.Options'),
        ),
    ]
