# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0018_activityschedule_enable_accept_reject'),
        ('hypernet', '0033_auto_20180305_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypernetnotification',
            name='job',
        ),
        migrations.AddField(
            model_name='hypernetnotification',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_job_id', to='iof.Activity'),
        ),
    ]
