# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerclients_customerpreferences'),
        ('options', '0003_options_module'),
        ('hypernet', '0035_auto_20180405_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hypernet_clients', to='customer.CustomerClients'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bin_sub_type_id', to='options.Options'),
        ),
    ]
