# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_options_module'),
        ('hypernet', '0036_auto_20180416_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetnotification',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notification_type_id', to='options.Options'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hypernetnotification',
            name='violation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violation_type_id', to='options.Options'),
        ),
    ]
