# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0038_auto_20180418_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='clients',
            new_name='client',
        ),
    ]
