# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iof', '0040_auto_20180427_0552'),
        ('hypernet', '0039_auto_20180423_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetnotification',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue_id', to='iof.ActivityQueue'),
        ),
    ]
