# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0040_hypernetnotification_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypernetnotification',
            name='queue',
        ),
    ]
