# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0041_remove_hypernetnotification_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetpostdata',
            name='validity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
