# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0042_auto_20180507_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='end_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
