# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180507_1101'),
        ('hypernet', '0043_auto_20180508_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdevice',
            name='connection_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecalibration',
            name='skip_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='skip_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
