# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0044_auto_20180523_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Module'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hypernet.DeviceType'),
        ),
    ]
