# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0045_auto_20180528_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceviolation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violation_device_id', to='hypernet.Entity'),
        ),
        migrations.AlterField(
            model_name='deviceviolation',
            name='violation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_violation_type', to='options.Options'),
        ),
    ]
