# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0046_auto_20180605_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdevice',
            name='primary_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
