# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0047_auto_20180607_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetnotification',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_data_device_id', to='hypernet.Entity'),
        ),
    ]
