# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0050_auto_20180620_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='assignments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='squad_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
