# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0051_auto_20180703_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetnotification',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
