# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0051_auto_20180703_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetpostdata',
            name='ambient_temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='ambient_temperature',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
