# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0052_auto_20180726_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetnotification',
            name='violation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violation_type_id', to='options.Options'),
        ),
    ]
