# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0053_auto_20180908_1454'),
        ('hypernet', '0053_auto_20180808_1631'),
    ]

    operations = [
    ]
