# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0054_merge_20180912_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetpostdata',
            name='active_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpostdata',
            name='inactive_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='active_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='inactive_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
