# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0055_auto_20180917_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='trip',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='trip',
            field=models.NullBooleanField(default=None),
        ),
    ]
