# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0056_auto_20180924_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypernetpostdata',
            name='trip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hypernetpredata',
            name='trip',
            field=models.BooleanField(default=False),
        ),
    ]
