# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20180427_1608'),
        ('hypernet', '0058_auto_20180924_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='skip_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skip_size_id', to='options.Options'),
        ),
    ]
