# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_customerpreferences_diesel_price'),
        ('options', '0004_auto_20180427_1608'),
        ('user', '0011_auto_20180530_1007'),
        ('hypernet', '0059_entity_skip_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('total_sum', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_area_id', to='hypernet.Entity')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.CustomerClients')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_contract_id', to='hypernet.Entity')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_contract_type_id', to='options.Options')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
            ],
        ),
    ]
