# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0060_invoicedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='invoice_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
