# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20180427_1608'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0026_customerpreferences_diesel_price'),
        ('user', '0011_auto_20180530_1007'),
        ('hypernet', '0062_auto_20181226_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1500)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_remove', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=True)),
                ('modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_assignment_device', to='hypernet.Entity')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_assignment_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Module')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.Options')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypernet.DeviceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device_assignment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
