# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0067_entity_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypernetpostdata',
            name='ctt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpostdata',
            name='debug_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='ctt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hypernetpredata',
            name='debug_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
