# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypernet', '0070_auto_20200924_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='standby_mode',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
